import { CardData } from "./cardItem/CardItem";

export const cardsData: CardData[] = [
    {
        title: "Eat Right For Your Exercise Regime",
        tags: ["Lifestyle"],
        autor: "Nick Bove",
        text: "Structured gripped tape invisible moulded cups for sauppor firm hold strong powermesh front liner sport detail. Warmth comfort hangs loosely from the body large pocket at the front full button…",
        img: "Rectangle.png",
        date: "April 8, 2018",
        views: "3K",
    },
    {
        title: "The Look: Perfect Balance",
        tags: ["Lifestyle"],
        autor: "Nick Bove",
        text: "Structured gripped tape invisible moulded cups for sauppor firm hold strong powermesh front liner sport detail. Warmth comfort hangs loosely from the body large pocket at the front full button…",
        img: "Rectangle-3.png",
        date: "April 8, 2018",
        views: "3K",
    },
    {
        title: "Fun Things to Do in Rome",
        tags: ["Style"],
        autor: "Nick Bove",
        text: "Structured gripped tape invisible moulded cups for sauppor firm hold strong powermesh front liner sport detail. Warmth comfort hangs loosely from the body large pocket at the front full button…",
        img: "Rectangle-6.png",
        date: "April 8, 2018",
        views: "3K",
    },
    {
        title: "24 Colorful Ceilings That Add Unexpected Contrast to Any Room",
        tags: ["Style"],
        autor: "Nick Bove",
        text: "Structured gripped tape invisible moulded cups for sauppor firm hold strong powermesh front liner sport detail. Warmth comfort hangs loosely from the body large pocket at the front full button…",
        img: "Rectangle-1.png",
        date: "April 8, 2018",
        views: "3K",
    },
    {
        title: "9 New Songs to Heat Up Your Fall Playlist",
        tags: ["Lifestyle"],
        autor: "Nick Bove",
        text: "Structured gripped tape invisible moulded cups for sauppor firm hold strong powermesh front liner sport detail. Warmth comfort hangs loosely from the body large pocket at the front full button…",
        img: "Rectangle-4.png",
        date: "April 8, 2018",
        views: "3K",
    },
    {
        title: "What You Need on Your Bedside Table",
        tags: ["Events"],
        autor: "Nick Bove",
        text: "Structured gripped tape invisible moulded cups for sauppor firm hold strong powermesh front liner sport detail. Warmth comfort hangs loosely from the body large pocket at the front full button…",
        img: "Rectangle-7.png",
        date: "April 8, 2018",
        views: "3K",
    },
    {
        title: "When Two Wheels Are Better Than Four",
        tags: ["Travel"],
        autor: "Nick Bove",
        text: "Structured gripped tape invisible moulded cups for sauppor firm hold strong powermesh front liner sport detail. Warmth comfort hangs loosely from the body large pocket at the front full button…",
        img: "Rectangle-2.png",
        date: "April 8, 2018",
        views: "3K",
    },
    {
        title: "26 Living Room Ideas from the Homes of Top Designers",
        tags: ["Travel"],
        autor: "Nick Bove",
        text: "Structured gripped tape invisible moulded cups for sauppor firm hold strong powermesh front liner sport detail. Warmth comfort hangs loosely from the body large pocket at the front full button…",
        img: "Rectangle-5.png",
        date: "April 8, 2018",
        views: "3K",
    },
    {
        title: "What Makes Your City’s Style Unique",
        tags: ["Music"],
        autor: "Nick Bove",
        text: "Structured gripped tape invisible moulded cups for sauppor firm hold strong powermesh front liner sport detail. Warmth comfort hangs loosely from the body large pocket at the front full button…",
        img: "Rectangle-8.png",
        date: "April 8, 2018",
        views: "3K",
    },
]